[package]
name = "log-light-state"
version = "0.1.0"
edition = "2018"
authors = [ "Billie Thompson <billie+git-mit@billiecodes.com>" ]
license = "Creative Commons Zero v1.0 Universal"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "ai", "neural-networks" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hueclient = "0.3.8"
csv = "1.1.3"
chrono = "0.4.13"
clap = "2.33.1"
indicatif = "0.15.0"
