name: Validate commits
"on":
  push:
    branches:
      - "*"
  pull_request: null
jobs:
  validate-commits:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.2
        name: Checkout repository
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2
        name: Validate commits
